PRUEBA
proyectoFinalSirun30A/Proyecto-Final1 pull request #10
Opened 2022-11-01 21:56 UTC by proyectoFinalSirun30A

2022-11-01 21:57 UTC, proyectoFinalSirun30A commented
estoy probando la funcionalidad de Git Hub

2022-11-02 00:30 UTC, Dante1704 approved these changes
esta muy bien esta prueba, esta lista para ser mergeada a main. cuando la mergees, tenes que eliminar el brunch.

2022-11-02 00:34 UTC, Dante1704 requested changes
tenes que borrar las <<<< y >>>>> para resolver el conflicto, cuando lo hagas solicitame review nuevamente y te lo apruebo para que lo mergees

2022-11-02 13:36 UTC, Juanlopez01 approved these changes

2022-11-02 13:36 UTC, Juanlopez01 commented
Para mi ta bien

2022-11-02 13:50 UTC, fsponton approved these changes
checked cambios realizados

2022-11-02 13:50 UTC, Dante1704 approved these changes
ok! aprobado podes hacer el merge

2022-11-02 14:05 UTC, closed without merging